program Comercial;

uses
  Forms,
  UPrincipal in 'UPrincipal.pas' {FrmPrincipal},
  DM in 'DM.pas' {IBDM: TDataModule},
  UClientes in 'UClientes.pas' {FrmEdClientes},
  UFornecedores in 'UFornecedores.pas' {FrmEdFornecedores},
  UParam in 'UParam.pas' {FrmEdParam},
  UPosCaixa in 'UPosCaixa.pas' {FrmPosCaixa},
  UProdutos in 'UProdutos.pas' {FrmEdProdutos},
  UCaixa in 'UCaixa.pas' {FrmEdCaixa},
  UCReceber in 'UCReceber.pas' {FrmEdCReceber},
  UCPagar in 'UCPagar.pas' {FrmEdCPagar},
  UEtiquetas in 'UEtiquetas.pas' {FrmEdEtiquetas},
  UVendedores in 'UVendedores.pas' {FrmEdVendedores},
  UGrupos in 'UGrupos.pas' {FrmEdGrupos},
  USubGrupo in 'USubGrupo.pas' {FrmEdSubGrupo},
  UCrecebidas in 'UCrecebidas.pas' {FrmEdCRecebidas},
  UCPagas in 'UCPagas.pas' {FrmEdCPagas},
  UTrCaixa in 'UTrCaixa.pas' {FrmTrCaixa},
  UQuitarConta in 'UQuitarConta.pas' {FrmQuitarConta},
  UNotaVenda in 'UNotaVenda.pas' {FrmNotaVenda},
  UItensVenda in 'UItensVenda.pas' {FrmItensVenda},
  UNotaCompra in 'UNotaCompra.pas' {FrmNotaCompra},
  UItensCompra in 'UItensCompra.pas' {FrmItensNota},
  UPesqClientes in 'UPesqClientes.pas' {FrmPesqClientes},
  UComissoes in 'UComissoes.pas' {FrmComissoes},
  UIcms in 'UIcms.pas' {FrmIcms},
  UClasTrib in 'UClasTrib.pas' {FrmClasTrib},
  URelDataCRec in 'URelDataCRec.pas' {FrmRelDataCRec},
  URelContReceber in 'URelContReceber.pas' {FrmRelContReceber},
  URelClientes in 'URelClientes.pas' {FrmRelClientes},
  URelFornecedores in 'URelFornecedores.pas' {FrmRelFornecedores},
  UPagarConta in 'UPagarConta.pas' {FrmPagarConta},
  URelFiltraEst in 'URelFiltraEst.pas' {FrmRelFiltraEst},
  URelEstoque in 'URelEstoque.pas' {FrmRelEstoque},
  URelFiltraCai in 'URelFiltraCai.pas' {FrmRelFiltraCai},
  URelCaixa in 'URelCaixa.pas' {FrmRelCaixa},
  URelCPagar in 'URelCPagar.pas' {FrmRelCPagar},
  URepEtiqueta in 'URepEtiqueta.pas' {FrmRepEtiqueta},
  URelEtiquetas in 'URelEtiquetas.pas' {FrmRelEtiquetas},
  UIncluirEtiq in 'UIncluirEtiq.pas' {FrmIncluirEtiq},
  UIncluirIcms in 'UIncluirIcms.pas' {FrmIncluirIcms},
  UIncluirtribcai in 'UIncluirtribcai.pas' {FrmIcluirTribCai},
  UIncluirTribut in 'UIncluirTribut.pas' {FrmIncluirTribut},
  UIncluirVend in 'UIncluirVend.pas' {FrmIncluirVend},
  UIncluirGrupo in 'UIncluirGrupo.pas' {FrmIncluirGrupo},
  UIncluirSubGrupo in 'UIncluirSubGrupo.pas' {FrmIncluirSubGrupo},
  URelComissoes in 'URelComissoes.pas' {FrmRelComissoes},
  UFechaVenda in 'UFechaVenda.pas' {FrmFechaVenda},
  UPrestacoes in 'UPrestacoes.pas' {FrmPrestacoes},
  UCadCheques in 'UCadCheques.pas' {FrmCadCheque},
  UBaixaEst in 'UBaixaEst.pas' {FrmBaixaEstoque},
  UEstrProd in 'UEstrProd.pas' {FrmEstrutProd},
  UEditaEstrut in 'UEditaEstrut.pas' {FrmEditaEstrut},
  URelEstrutura in 'URelEstrutura.pas' {FrmRelEstrutura},
  UMovimentacao in 'UMovimentacao.pas' {FrmMovimentacao},
  URelMovimento in 'URelMovimento.pas' {FrmRelMovimentacao},
  URelGrupos in 'URelGrupos.pas' {Relgrupos},
  URelSubGrupos in 'URelSubGrupos.pas' {RelSubgrupo},
  UPrestNComp in 'UPrestNComp.pas' {FrmPrestNCompra},
  USuperUsuario in 'USuperUsuario.pas' {FrmSuperUsuario},
  URecibo in 'URecibo.pas' {FrmRecibo},
  UEdNotaCom in 'UEdNotaCom.pas' {FrmEdNotaCom},
  UEdItensNota in 'UEdItensNota.pas' {FrmEdItensNota},
  ULogErros in 'ULogErros.pas' {FrmLogErros},
  UInventario in 'UInventario.pas' {FrmInventario},
  UFiltraEst in 'UFiltraEst.pas' {FrmFiltraEst},
  URelInventario in 'URelInventario.pas' {FrmInventaRel},
  URelRegInven in 'URelRegInven.pas' {FrmRelRegInven},
  UTermoAberEnc in 'UTermoAberEnc.pas' {FrmTermoAberEnc},
  UTipoServ in 'UTipoServ.pas' {FrmTipoServ},
  UOrdemServ1 in 'UOrdemServ1.pas' {FrmOrdemServ1},
  UOrdemServ2 in 'UOrdemServ2.pas' {FrmOrdemServ2},
  URelOrdemServ in 'URelOrdemServ.pas' {FrmRelOrdemServ},
  URelCliNiver in 'URelCliNiver.pas' {FrmRelCliNiver},
  UFinanOrdem in 'UFinanOrdem.pas' {FrmFinanOrdem},
  UCopiaSeg in 'UCopiaSeg.pas' {FrmCopiaSeg},
  URanking in 'URanking.pas' {FrmRanking},
  UNotaFiscal in 'UNotaFiscal.pas' {FrmNotaFiscal},
  UPesqProd in 'UPesqProd.pas' {FrmPesqProd},
  UNotaFiscal1 in 'UNotaFiscal1.pas' {FrmNotaFiscal1},
  URelNotaFiscal in 'URelNotaFiscal.pas' {FrmRelNotaFiscal},
  UFechaVenda1 in 'UFechaVenda1.pas' {FrmFechaVenda1},
  UPrestacoes1 in 'UPrestacoes1.pas' {FrmPrestacoes1},
  UEstados in 'UEstados.pas' {FrmEstados},
  URelEstMinimo in 'URelEstMinimo.pas' {FrmRelEstMinimo},
  USomarCreceber in 'USomarCreceber.pas' {FrmSomarCReceber},
  UConvenio in 'UConvenio.pas' {FrmConvenio},
  UFiltraConvenio in 'UFiltraConvenio.pas' {FrmFiltraConvenio},
  URelConvenioCli in 'URelConvenioCli.pas' {FrmRelConvenioCli},
  UCheque in 'UCheque.pas' {FrmCheques},
  UChequeComp in 'UChequeComp.pas' {FrmChequeComp},
  UCartao in 'UCartao.pas' {FrmCartao},
  UEdCartao in 'UEdCartao.pas' {FrmEdCartao},
  UEscolheImp in 'UEscolheImp.pas' {FrmEscolheImp},
  Ufuncoes in 'C:\TI\Utils\Ufuncoes.pas',
  Urelcadastr in 'Urelcadastr.pas' {Relcadastro},
  Uprecos in 'Uprecos.pas' {Frmprecos},
  Ucd in 'Ucd.pas' {Frmedcondi},
  UEDCD in 'UEDCD.pas' {FrmEDCD},
  Ucontrato in 'Ucontrato.pas' {Frmcontrato},
  Urelpagcom in 'Urelpagcom.pas' {QRListForm},
  Uitvnd in 'Uitvnd.pas' {Frmitvnd},
  Umodopgto in 'Umodopgto.pas' {Frmmodopgto},
  Uedobsrec in 'Uedobsrec.pas' {Frmedobsrec},
  Uzoomvd in 'Uzoomvd.pas' {Frmzoomvd},
  UcarneMP in 'UcarneMP.pas' {relcarneMP},
  UListaProdutos in 'UListaProdutos.pas' {FrmProdutos},
  Urelrecibo2 in 'Urelrecibo2.pas' {RelRecibo2},
  Urelvendas in 'Urelvendas.pas' {RElvendas},
  Uprinter in 'Uprinter.pas' {Frmprinter},
  tbPrn in 'C:\TI\Utils\TBPRN.PAS',
  UfrmresumoCX in 'UfrmresumoCX.pas' {FrmresumoCX},
  Urelfluxocx in 'Urelfluxocx.pas' {RelFluxocx},
  URelvendasP in 'URelvendasP.pas' {RelvendasP},
  Urelresvende in 'Urelresvende.pas' {RelResVende},
  Urelitvend1 in 'Urelitvend1.pas' {Relitvend1},
  Urelitvend2 in 'Urelitvend2.pas' {Relitvend2},
  ULimpeza in 'ULimpeza.pas' {FrmLimpeza},
  UMostraLimp in 'UMostraLimp.pas' {FrmDadoslimp},
  Uavisos in 'Uavisos.pas' {FrmAvisos},
  Urelavisos in 'Urelavisos.pas' {RelAvisos},
  Upagmult in 'Upagmult.pas' {FrmPagMult},
  Uspcpesq in 'Uspcpesq.pas' {FrmSPCPesq},
  Uetiqcli in 'Uetiqcli.pas' {EtiqCli},
  Uchkspc in 'Uchkspc.pas' {FrmCHKSPC},
  USelCli in 'USelCli.pas' {FrmSelCli},
  Urelcli_1 in 'Urelcli_1.pas' {Relcli_1: TQuickRep},
  Uzoom1 in 'Uzoom1.pas' {FrmZoom},
  Uvariosmodos in 'Uvariosmodos.pas' {Frm_Pgmodos},
  Uconfcli in 'Uconfcli.pas' {frmconfcli},
  Urelmovdia in 'Urelmovdia.pas' {Relmovdia: TQuickRep},
  RelSPC_ in 'RelSPC_.pas' {RelSPC: TQuickRep},
  UBematech_4200 in 'UBematech_4200.pas',
  UTetesImp in 'UTetesImp.pas' {FrmTesteImp},
  Utesteimp in 'Utesteimp.pas' {RELTESTE: TQuickRep},
  UItensVenda1 in 'UItensVenda1.pas' {FrmItensVenda1},
  UPrestacoes2 in 'UPrestacoes2.pas' {FrmPrestacoes2};

{$R *.RES}
begin
    Application.Initialize;
    Application.Title := ' > Sistema de Gestão Comercial <';
    if HPrevInst = 0 then
    begin
      Application.CreateForm(TFrmPrincipal, FrmPrincipal);
      Application.CreateForm(TIBDM, IBDM);
      Application.CreateForm(TFrmItensVenda1, FrmItensVenda1);
      Application.CreateForm(TFrmPrestacoes2, FrmPrestacoes2);
      Application.Run;
    end ;
end.
